export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const SET_SETTINGS_LOADING = "SET_SETTINGS_LOADING";
export const SET_SETTINGS_FAILED = "SET_SETTINGS_FAILED";
export const SET_SETTINGS_VARIANTS = "SET_SETTINGS_VARIANTS";

export const GET_RESULTS_REQUEST = "GET_RESULTS_REQUEST";
export const SET_RESULTS_LOADING = "SET_RESULTS_LOADING";
export const SET_RESULTS_SUCCESS = "SET_RESULTS_SUCCESS";
export const SET_RESULTS_FAILED = "SET_RESULTS_FAILED";

export const UPDATE_RESULTS_REQUEST = "UPDATE_RESULTS_REQUEST";
